# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170713_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='c_value',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
