# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sitedetail_c_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedetail',
            name='c_value',
        ),
    ]
